# Blink Managed Infrastructure
# Auto-generated by Blink Agent
# Do not edit manually


# Service Module Block
#
# Appended to main.tf for each subsequent service.
# Variables for this service are appended to variables.tf separately.

# ============================================
# Security Group: demo_api
# (per-service — independent ports from other services)
# ============================================

resource "aws_security_group" "demo_api" {
  name        = "blink-demo_api-sg"
  description = "Security group for service demo_api"
  vpc_id      = module.vpc.vpc_id

  dynamic "ingress" {
    for_each = var.demo_api_ingress_ports
    content {
      from_port   = ingress.value
      to_port     = ingress.value
      protocol    = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
      description = "Port ${ingress.value}"
    }
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound"
  }

  tags = {
    Name      = "blink-demo_api-sg"
    Service   = "demo_api"
    ManagedBy = "blink"
  }
}

# ============================================
# Service: demo_api
# ============================================

module "service_demo_api" {
  source = "./modules/ec2"

  service_name         = "demo_api"
  instance_type        = var.demo_api_instance_type
  vpc_id               = module.vpc.vpc_id
  subnet_id            = module.vpc.public_subnet_id
  security_group_id    = aws_security_group.demo_api.id
  iam_instance_profile = module.iam.instance_profile_name
  use_elastic_ip       = var.demo_api_use_elastic_ip
}


output "service_demo_api_ip" {
  description = "Service public IP"
  value       = module.service_demo_api.public_ip
}

output "service_demo_api_instance_id" {
  description = "Service EC2 instance ID (for SSM)"
  value       = module.service_demo_api.instance_id
}

output "service_demo_api_url" {
  description = "Service URL"
  value       = "http://${module.service_demo_api.public_ip}:3000"
}
