# Blink Managed Infrastructure
# Auto-generated by Blink Agent
# Do not edit manually


# Service Module Block
#
# Appended to main.tf for each subsequent service.
# Variables for this service are appended to variables.tf separately.

# ============================================
# Security Group: demo_test
# (per-service — independent ports from other services)
# ============================================

resource "aws_security_group" "demo_test" {
  name        = "blink-demo_test-sg"
  description = "Security group for service demo_test"
  vpc_id      = module.vpc.vpc_id

  dynamic "ingress" {
    for_each = var.demo_test_ingress_ports
    content {
      from_port   = ingress.value
      to_port     = ingress.value
      protocol    = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
      description = "Port ${ingress.value}"
    }
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound"
  }

  tags = {
    Name      = "blink-demo_test-sg"
    Service   = "demo_test"
    ManagedBy = "blink"
  }
}

# ============================================
# Service: demo_test
# ============================================

module "service_demo_test" {
  source = "./modules/ec2"

  service_name         = "demo_test"
  instance_type        = var.demo_test_instance_type
  vpc_id               = module.vpc.vpc_id
  subnet_id            = module.vpc.public_subnet_id
  security_group_id    = aws_security_group.demo_test.id
  iam_instance_profile = module.iam.instance_profile_name
  use_elastic_ip       = var.demo_test_use_elastic_ip
}


output "service_demo_test_ip" {
  description = "Service public IP"
  value       = module.service_demo_test.public_ip
}

output "service_demo_test_instance_id" {
  description = "Service EC2 instance ID (for SSM)"
  value       = module.service_demo_test.instance_id
}

output "service_demo_test_url" {
  description = "Service URL"
  value       = "http://${module.service_demo_test.public_ip}:3000"
}

# ============================================
# Database: demo_test_db
# Engine: postgres — managed by Blink
# ============================================

module "db_demo_test_db" {
  source = "./modules/rds"

  name                  = "demo_test_db"
  vpc_id                = module.vpc.vpc_id
  subnet_ids            = module.vpc.public_subnet_ids
  app_security_group_id = aws_security_group.demo_test.id
  engine                = var.demo_test_db_db_engine
  engine_version        = var.demo_test_db_db_engine_version
  instance_class        = var.demo_test_db_db_instance_class
  db_name               = var.demo_test_db_db_name
  db_username           = var.demo_test_db_db_username
  multi_az              = var.demo_test_db_db_multi_az
}

output "db_demo_test_db_endpoint" {
  description = "RDS endpoint (host:port) for demo_test_db"
  value       = module.db_demo_test_db.endpoint
}

output "db_demo_test_db_address" {
  description = "RDS hostname for demo_test_db"
  value       = module.db_demo_test_db.address
}

output "db_demo_test_db_port" {
  description = "RDS port for demo_test_db"
  value       = module.db_demo_test_db.port
}

output "db_demo_test_db_password_ssm" {
  description = "SSM Parameter Store path containing DB password for demo_test_db"
  value       = module.db_demo_test_db.db_password_ssm_path
}
