# Blink Managed Variables
# Auto-generated by Blink Agent
# Do not edit manually

# ============================================
# Per-Service Variables: demo_test
# ============================================

variable "demo_test_instance_type" {
  description = "EC2 instance type for demo_test"
  type        = string
  default     = "t3.small"
}

variable "demo_test_ingress_ports" {
  description = "Ports to open for demo_test"
  type        = list(number)
  default     = [80,443,22]
}

variable "demo_test_use_elastic_ip" {
  description = "Use Elastic IP for demo_test"
  type        = bool
  default     = true
}

# ============================================
# RDS Variables: demo_test_db
# ============================================

variable "demo_test_db_db_engine" {
  description = "Database engine for demo_test_db"
  type        = string
  default     = "postgres"
}

variable "demo_test_db_db_engine_version" {
  description = "Database engine version for demo_test_db"
  type        = string
  default     = "15.4"
}

variable "demo_test_db_db_instance_class" {
  description = "RDS instance class for demo_test_db"
  type        = string
  default     = "db.t3.micro"
}

variable "demo_test_db_db_name" {
  description = "Database name for demo_test_db"
  type        = string
  default     = "demo_test"
}

variable "demo_test_db_db_username" {
  description = "Database master username for demo_test_db"
  type        = string
  default     = "blinkadmin"
}

variable "demo_test_db_db_multi_az" {
  description = "Enable Multi-AZ deployment for demo_test_db"
  type        = bool
  default     = false
}
