# Blink Managed Variables
# Auto-generated by Blink Agent
# Do not edit manually

# ============================================
# Per-Service Variables: demo_api
# ============================================

variable "demo_api_instance_type" {
  description = "EC2 instance type for demo_api"
  type        = string
  default     = "t3.small"
}

variable "demo_api_ingress_ports" {
  description = "Ports to open for demo_api"
  type        = list(number)
  default     = [80,443,22]
}

variable "demo_api_use_elastic_ip" {
  description = "Use Elastic IP for demo_api"
  type        = bool
  default     = true
}
